### PR TITLE
Depend on explicit jquery version.

### PR DESCRIPTION
**Pull request by umpirsky**
BTW, what do you think about moving javascripts block to the bottom, right before `</body>`?

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Big +1, I kept forgetting about this, would you mind adding it to this PR? Thanks!

**Comment by umpirsky** [comment]
I requires some additional changes, I don't want to break the demo now, we will handle that in separate PR.

One place where it can break is [Backend/Zone/_form.html.twig](https://github.com/Sylius/Sylius-Sandbox/blob/master/src/Sylius/Bundle/SandboxBundle/Resources/views/Backend/Zone/_form.html.twig) where javascripts should be moved to some template which extends layout and `{{ parent() }}` added.

@pjedrzejewski Are you aware of any possible breaks other then this?

**Comment by pjedrzejewski** [comment]
Hm... nope... this is the only place for js other than the layout.

**Comment by umpirsky** [comment]
OK, I'll fix this today ;)

**Comment by umpirsky** [comment]
Fixed.

**Comment by pjedrzejewski** [comment]
Thank you sir!

**Pull request merged**
