### PR TITLE
Knp menu

### PR DESCRIPTION
**Pull request by umpirsky**
Initial knp menu implementation.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Awesome! I'll do a quick review, but could you first rebase your PR, please? Thanks!

**Comment by umpirsky** [comment]
@pjedrzejewski Great. Rebased.

**Comment by pjedrzejewski** [comment]
Hmmm, there are still some conflicts, can you resolve them please? I haven't commited anything so you probably missed something. =) Thanks!

"**This pull request cannot be automatically merged.**"

**Comment by umpirsky** [comment]
Hehum.

I started with

```
git rebase -f upstream/master
```

resolved some conflicts in composer files, then

```
git rebase --continue
```

again resolved some conflicts in composer files, and then came to this:

```
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git status
# Not currently on any branch.
nothing to commit (working directory clean)
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git rebase --continue
Applying: Updated vendors.
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem run "git rebase --continue".
If you would prefer to skip this patch, instead run "git rebase --skip".
To restore the original branch and stop rebasing run "git rebase --abort".

umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git add composer.json
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git add composer.lock
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git status
# Not currently on any branch.
nothing to commit (working directory clean)
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git rebase --continue
Applying: Updated vendors.
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem run "git rebase --continue".
If you would prefer to skip this patch, instead run "git rebase --skip".
To restore the original branch and stop rebasing run "git rebase --abort".

umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git status
# Not currently on any branch.
nothing to commit (working directory clean)
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git push -f origin knp-menu 
Everything up-to-date
```

Is it ok now?
Am I dogin something wrong?

**Comment by pjedrzejewski** [comment]
Heh, you rebased while not being on any branch, so you did it on detached HEAD. You should first checkout the `knp-menu` branch, then rebase. As you see, now it says everything is up to date, because the rebasing was done on no branch. I didn't even know git allows doing rebase on detached HEAD. =P

**Comment by umpirsky** [comment]
I was on knp-menu branch, but rebase throwed me out:

```
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git status
# On branch knp-menu
nothing to commit (working directory clean)
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git rebase -f upstream/master 
First, rewinding head to replay your work on top of it...
Applying: Updated vendors.
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging composer.json
Auto-merging composer.lock
CONFLICT (content): Merge conflict in composer.lock
Failed to merge in the changes.
Patch failed at 0001 Updated vendors.

When you have resolved this problem run "git rebase --continue".
If you would prefer to skip this patch, instead run "git rebase --skip".
To restore the original branch and stop rebasing run "git rebase --abort".

umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git status
# Not currently on any branch.
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#   modified:   composer.json
#
# Unmerged paths:
#   (use "git reset HEAD <file>..." to unstage)
#   (use "git add/rm <file>..." as appropriate to mark resolution)
#
#   both modified:      composer.lock
#
umpirsky@umpirsky:~/Projects/PHP/sylius.umpirsky.loc$ git status
# Not currently on any branch.
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#   modified:   composer.json
#   modified:   composer.lock
#

```

Am I doing something wrong? If not what to do next?

**Comment by pjedrzejewski** [comment]
You need to call `git rebase --continue` then if it's done --- `git push remote/branch -f`.

**Comment by umpirsky** [comment]
I did:

```
umpirsky@desktop:~/Projects/PHP/sylius.umpirsky.loc$ git rebase --continue
Applying: Updated vendors.
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem run "git rebase --continue".
If you would prefer to skip this patch, instead run "git rebase --skip".
To restore the original branch and stop rebasing run "git rebase --abort".

umpirsky@desktop:~/Projects/PHP/sylius.umpirsky.loc$ git status
# Not currently on any branch.
nothing to commit (working directory clean)
umpirsky@desktop:~/Projects/PHP/sylius.umpirsky.loc$ git push -f origin knp-menu 
Everything up-to-date
```

I guess it's rebased now, but this `Everything up-to-date` looks strange.

**Comment by pjedrzejewski** [comment]
You should read console messages, you need to `git add` files after you fixed conflicts. I'll get your fork on my local and check that...

**Comment by umpirsky** [comment]
Ah, yes, I'll try again.

**Comment by pjedrzejewski** [comment]
I tried to merge it cleanly but I think you started this branch not from master and after all this rebasing and mergin it's totally messed by both of us. =( sorry, could you please open seperate PR? I'm closing this as I'm getting some weird results after merging and rebasing.

**Comment by umpirsky** [comment]
No problem, I'll move this to a new branch and fix new PR. Sorry for the mess.

**Pull request closed without merging**
