### PR TITLE
Ckeditor

### PR DESCRIPTION
**Pull request by umpirsky**
Added CKEditor to sandbox app. 

This can be useful until we implement attributes, and I think demo will look reacher.

### CODE REVIEW

**Comment by pjedrzejewski** [comment]
Product descriptions already have markdown support so this relatively heavy is valid for main Sylius app. Not necessarily CKEditor, but some other for sure will be included.

**Comment by umpirsky** [comment]
Cool. Can you tell which ones, I'm interested to integrate one into my webshop?

**Comment by pjedrzejewski** [comment]
CKEditor is fine, but there are also for example TinyMCE, markItUp!, there is plenty to pick from. ;) For Sylius, not sure yet as it's rather matter of interface, we're definitely not there yet. But maybe something cool like CreateJS for inline editing? We'll see that later.

**Comment by umpirsky** [comment]
I'm early adopter, so I must think fast about this things :)

**Pull request closed without merging**
